### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by rubenwardy** [eXpl0it3r/sfmlprojects#8]
the links on sfmlprojects are relative, meaning that you can end up on https://sfmlprojects.org/libraries/about instead of https://sfmlprojects.org/about
also, the SFML projects logo can lead you to https://sfmlprojects.org/libraries/home

**Comment by eXpl0it3r** [comment]
Hmmm only saw this issue just now.

Steps to reproduce:

- Navigate to https://sfmlprojects.org/libraries/ including the trailing slash!
- Footer navigation to other sites is now broken

**Comment by eXpl0it3r** [comment]
Will be fixed with the next page update

**Comment by rubenwardy** [comment]
I'd completely forgotten about this
